# Generated by Django 5.2.1 on 2025-06-21 11:37

import django.db.models.deletion
import incomes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('_name_encrypted', models.CharField(db_column='name', max_length=255)),
                ('user', models.ForeignKey(help_text='The user who owns this category.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['_name_encrypted'],
                'unique_together': {('user', '_name_encrypted')},
            },
            bases=(incomes.models.OwnerProtectedDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('_amount_encrypted', models.CharField(db_column='amount', max_length=255)),
                ('_description_encrypted', models.TextField(db_column='description', default='')),
                ('date', models.DateField()),
                ('recurring', models.CharField(choices=[('NO', 'No Recurrence'), ('MO', 'Monthly'), ('QO', 'Quarterly'), ('SO', 'Semi-annually'), ('YO', 'Annually')], default='NO', max_length=2)),
                ('currency', models.CharField(choices=[('JOD', 'Jordanian Dinar'), ('SAR', 'Saudi Riyal'), ('TRY', 'Turkish Lira'), ('USD', 'US Dollar')], default='USD', help_text='Currency of the income.', max_length=3)),
                ('expiration_date', models.DateField(blank=True, default=incomes.models.default_expiration_date, help_text='The date after which this income is considered expired.', null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incomes.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Income',
                'verbose_name_plural': 'Incomes',
                'ordering': ['-date'],
            },
            bases=(incomes.models.OwnerProtectedDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_whatsapp_number_encrypted', models.CharField(db_column='twilio_to_whatsapp_number', help_text='The WhatsApp number to send reminders to for this user.', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
