# Generated by Django 5.0.6 on 2024-06-14 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='recurring',
            field=models.CharField(choices=[('NO', 'No Recurrence'), ('MO', 'Monthly'), ('QO', 'Quarterly'), ('SO', 'Semi-annually')], default='NO', max_length=2),
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incomes.category'),
        ),
    ]
