# Generated by Django 5.2.1 on 2025-05-13 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0002_income_recurring_alter_income_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-date'], 'verbose_name': 'Income', 'verbose_name_plural': 'Incomes'},
        ),
        migrations.AddField(
            model_name='income',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name='income',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='amount_positive'),
        ),
    ]
