# Generated by Django 5.2.1 on 2025-05-13 08:57

import incomes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0003_alter_category_options_alter_income_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='expiration_date',
            field=models.DateField(blank=True, default=incomes.models.default_expiration_date, help_text='The date after which this income is considered expired.', null=True),
        ),
    ]
