# Generated by Django 5.2.1 on 2025-05-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0008_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.CharField(max_length=255),
        ),
    ]
