# Generated by Django 5.2.1 on 2025-05-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0009_alter_income_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.CharField(db_column='amount', max_length=255),
        ),
        migrations.RenameField(
            model_name='income',
            old_name='amount',
            new_name='_amount_encrypted',
        ),
        migrations.AlterField(
            model_name='income',
            name='description',
            field=models.TextField(blank=True, db_column='description', null=True),
        ),
        migrations.RenameField(
            model_name='income',
            old_name='description',
            new_name='_description_encrypted',
        ),
    ]
