# Generated by Django 5.2.1 on 2025-05-15 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0010_alter_income_amount_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='income',
            name='amount_positive',
        ),
    ]
