# Generated by Django 5.2.1 on 2025-05-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0011_remove_income_amount_positive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='_description_encrypted',
            field=models.TextField(db_column='description', default=''),
        ),
    ]
