# Generated by Django 5.2.1 on 2025-05-15 08:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0012_alter_income__description_encrypted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['_name_encrypted'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_column='name', max_length=255),
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='_name_encrypted',
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('user', '_name_encrypted')},
        ),
    ]
