# Generated by Django 5.2.1 on 2025-05-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0014_category_deleted_at_category_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='recurring',
            field=models.CharField(choices=[('NO', 'No Recurrence'), ('MO', 'Monthly'), ('QO', 'Quarterly'), ('SO', 'Semi-annually'), ('YO', 'Annually')], default='NO', max_length=2),
        ),
    ]
