# Generated by Django 5.2.1 on 2025-06-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0015_alter_income_recurring'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='currency',
            field=models.CharField(choices=[('JOD', 'Jordanian Dinar'), ('SAR', 'Saudi Riyal'), ('TRY', 'Turkish Lira'), ('USD', 'US Dollar')], default='USD', help_text='Currency of the income.', max_length=3),
        ),
    ]
