# Generated by Django 5.2.1 on 2025-06-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0016_income_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='twilio_to_whatsapp_number',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='_whatsapp_number_encrypted',
            field=models.CharField(blank=True, db_column='twilio_to_whatsapp_number', help_text='The WhatsApp number to send reminders to for this user.', max_length=255, null=True),
        ),
    ]
