# Generated by Django 5.2.1 on 2025-06-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0017_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='_whatsapp_number_encrypted',
            field=models.CharField(db_column='twilio_to_whatsapp_number', default=0, help_text='The WhatsApp number to send reminders to for this user.', max_length=255),
            preserve_default=False,
        ),
    ]
